import { createStudioApp } from "../../packages/studio-server/src/index";

type DevelopmentEnvironment = { DB: D1Database; SAVIA_PLUGIN_DEV_KEY?: string };

/** Only mounted by the local Wrangler entry generated by pnpm dev. */
export async function handlePluginDevelopment(
  request: Request,
  env: DevelopmentEnvironment,
): Promise<Response> {
  const url = new URL(request.url);
  if (
    !env.SAVIA_PLUGIN_DEV_KEY ||
    !["127.0.0.1", "localhost", "[::1]"].includes(url.hostname)
  )
    return new Response("Not found", { status: 404 });
  // This endpoint is CLI-only. Reject browser-origin requests, including opaque iframes.
  if (
    request.headers.has("origin") ||
    request.headers.get("authorization") !==
      `Bearer ${env.SAVIA_PLUGIN_DEV_KEY}`
  )
    return new Response("Unauthorized", { status: 401 });
  if (request.method === "GET" && url.pathname === "/__dev/plugins/health")
    return Response.json({ development: true });
  if (request.method !== "POST" || url.pathname !== "/__dev/plugins/install")
    return new Response("Not found", { status: 404 });
  const tenant = url.searchParams.get("tenant");
  if (
    !tenant ||
    !/^(0|[1-9]\d*)$/.test(tenant) ||
    !Number.isSafeInteger(Number(tenant))
  )
    return new Response("A numeric tenant is required", { status: 400 });
  const exists = await env.DB.prepare(
    "SELECT id FROM tenants WHERE id=? AND is_active=1",
  )
    .bind(Number(tenant))
    .first();
  if (!exists) return new Response("Unknown local tenant", { status: 404 });
  // Retain installed code, but reclaim only artifacts created by this local tool.
  // Release uploads and all collection records remain untouched.
  await env.DB.prepare(
    `CREATE TABLE IF NOT EXISTS savia_local_plugin_builds (
    tenant_id TEXT NOT NULL, id TEXT NOT NULL, version TEXT NOT NULL,
    PRIMARY KEY (tenant_id,id,version))`,
  ).run();
  await env.DB.prepare(
    `DELETE FROM plugin_store_artifacts
    WHERE tenant_id=? AND EXISTS (
      SELECT 1 FROM savia_local_plugin_builds d
      WHERE d.tenant_id=plugin_store_artifacts.tenant_id AND d.id=plugin_store_artifacts.id AND d.version=plugin_store_artifacts.version
    ) AND NOT EXISTS (
      SELECT 1 FROM studio_extension_installations i
      WHERE i.tenant_id=plugin_store_artifacts.tenant_id AND i.id=plugin_store_artifacts.id AND i.version=plugin_store_artifacts.version
    )`,
  )
    .bind(`tenant:${tenant}`)
    .run();
  await env.DB.prepare(
    `DELETE FROM savia_local_plugin_builds WHERE tenant_id=? AND NOT EXISTS (
    SELECT 1 FROM plugin_store_artifacts a WHERE a.tenant_id=savia_local_plugin_builds.tenant_id AND a.id=savia_local_plugin_builds.id AND a.version=savia_local_plugin_builds.version
  )`,
  )
    .bind(`tenant:${tenant}`)
    .run();
  const studio = createStudioApp(`tenant:${tenant}`, { seedObjects: [] });
  const upload = await studio.request(
    "http://development.internal/api/plugin-store/upload",
    {
      method: "POST",
      headers: { "content-type": request.headers.get("content-type") ?? "" },
      body: await request.arrayBuffer(),
    },
    env,
  );
  if (!upload.ok) return upload;
  const { data } = (await upload.json()) as {
    data: { id: string; version: string };
  };
  await env.DB.prepare(
    "INSERT OR IGNORE INTO savia_local_plugin_builds(tenant_id,id,version) VALUES (?,?,?)",
  )
    .bind(`tenant:${tenant}`, data.id, data.version)
    .run();
  const installed = await studio.request(
    `http://development.internal/api/extensions/${encodeURIComponent(data.id)}/install`,
    {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ version: data.version }),
    },
    env,
  );
  if (!installed.ok) return installed;
  return Response.json({ data: { ...data, tenant: Number(tenant) } });
}
