import { describe, expect, it } from "vitest";
import { inspect } from "node:util";
import { postgresParameters } from "../src/postgres/parameters";
import { openPostgresDatabase } from "../src/postgres/database";
import {
  postgresTestsRequired,
  postgresTestUrl,
  withPostgresFixture,
} from "./postgres-fixture";

describe("PostgreSQL placeholders", () => {
  it("redacts malformed connection URLs", () => {
    let failure: unknown;
    try {
      openPostgresDatabase({
        connectionString: "postgres://user:dummysecret@[broken",
        schema: "savia_core",
        maxConnections: 1,
      });
    } catch (error) {
      failure = error;
    }
    expect(failure).toBeInstanceOf(Error);
    expect(inspect(failure)).not.toContain("dummysecret");
  });
  it("preserves literals, identifiers, nested comments and dollar quoting", () => {
    const sql = `SELECT '?' AS "?", $$?$$, $body$?$body$, E'it\\'s ?', 'it''s ?', ? -- ?\n /* ? /* ? */ */ , ?`;
    expect(postgresParameters(sql)).toEqual({
      text: sql.replace(", ? --", ", $1 --").replace(" , ?", " , $2"),
      parameterCount: 2,
    });
  });
  it("rejects malformed quoting and mixed native parameters", () => {
    for (const sql of [
      "SELECT 'oops",
      "SELECT /* oops",
      "SELECT $x$oops",
      "SELECT ?, $1",
      "SELECT ?1",
    ])
      expect(() => postgresParameters(sql)).toThrow();
  });
});

describe.skipIf(!postgresTestUrl && !postgresTestsRequired)(
  "live PostgreSQL adapter",
  () => {
    it("normalizes values, metadata and empty raw headers", async () =>
      withPostgresFixture(async (db) => {
        await db.exec(
          "CREATE TABLE item (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, value TEXT, data BYTEA)",
        );
        const insert = db.prepare(
          "INSERT INTO item(value,data) VALUES (?,?) RETURNING id",
        );
        const result = await insert.bind("first", Buffer.from([0, 255])).run();
        expect(result.meta).toMatchObject({
          changes: 1,
          last_row_id: 1,
          rows_written: 1,
        });
        expect(await db.prepare("SELECT value,data FROM item").first()).toEqual(
          { value: "first", data: [0, 255] },
        );
        expect(
          await db.prepare("SELECT ?::text AS value").bind(null).first("value"),
        ).toBeNull();
        expect(
          await db
            .prepare("SELECT 12345678901234567890.123::numeric AS n")
            .first("n"),
        ).toBe("12345678901234567890.123");
        expect(
          await db
            .prepare("SELECT ?::bytea AS bytes")
            .bind(new Uint8Array([1, 2]).buffer)
            .first("bytes"),
        ).toEqual([1, 2]);
        expect(() => insert.bind(undefined, null)).toThrow(/D1_TYPE_ERROR/);
        expect(() => insert.bind(Number.MAX_SAFE_INTEGER + 1, null)).toThrow(
          /D1_TYPE_ERROR/,
        );
        expect(await insert.bind("second", null).first("id")).toBe(2);
        expect(
          (await db.prepare("SELECT * FROM item").all()).meta.changes,
        ).toBe(0);
        expect(
          await db
            .prepare("SELECT id,value FROM item WHERE false")
            .raw({ columnNames: true }),
        ).toEqual([["id", "value"]]);
        await expect(
          db.prepare("SELECT 9007199254740992::bigint AS n").first(),
        ).rejects.toThrow(/safe integer/);
        await expect(insert.run()).rejects.toThrow(/binding/);
        await expect(db.prepare("SELECT 1; SELECT 2").all()).rejects.toThrow();
      }));
    it("isolates concurrent batches, rolls back failure and rejects foreign statements", async () =>
      withPostgresFixture(async (db, url) => {
        await db.exec("CREATE TABLE item(id INTEGER PRIMARY KEY, value TEXT)");
        const insert = (id: number) =>
          db.prepare("INSERT INTO item VALUES (?,?)").bind(id, String(id));
        const results = await Promise.allSettled([
          db.batch([insert(1), db.prepare("SELECT pg_sleep(0.03)"), insert(1)]),
          db.batch([insert(2), insert(3)]),
        ]);
        expect(results.map((r) => r.status)).toEqual(["rejected", "fulfilled"]);
        expect(
          await db.prepare("SELECT id FROM item ORDER BY id").raw(),
        ).toEqual([[2], [3]]);
        expect(
          (await db.prepare("UPDATE item SET value='ok'").run()).meta.changes,
        ).toBe(2);
        const other = openPostgresDatabase({
          connectionString: url,
          schema: "savia_core",
          maxConnections: 1,
        });
        try {
          await expect(
            db.batch([insert(4), other.prepare("SELECT 1")]),
          ).rejects.toThrow(/another database/);
        } finally {
          await other.close();
        }
        expect(
          await db.prepare("SELECT count(*) AS n FROM item").first("n"),
        ).toBe(2);
      }));
  },
);

it.skipIf(!postgresTestUrl && !postgresTestsRequired)(
  "recovers from an administratively terminated idle connection without exposing its error",
  async () => {
    await withPostgresFixture(async (db, connectionString) => {
      const other = openPostgresDatabase({
        connectionString,
        schema: "savia_core",
        maxConnections: 1,
      });
      try {
        const pid = await db
          .prepare("SELECT pg_backend_pid() AS pid")
          .first<number>("pid");
        // This promise observes removal only, so no credential-bearing error enters assertions.
        const removed = new Promise<void>((resolve) =>
          db.pool.once("remove", () => resolve()),
        );
        expect(
          await other
            .prepare("SELECT pg_terminate_backend(?) AS terminated")
            .bind(pid)
            .first("terminated"),
        ).toBe(true);
        await removed;
        const replacement = await db
          .prepare("SELECT pg_backend_pid() AS pid")
          .first<number>("pid");
        expect(replacement).not.toBe(pid);
        expect(await db.prepare("SELECT 1 AS value").first("value")).toBe(1);
      } finally {
        let socketClosed = false;
        other.pool.once("remove", () => {
          socketClosed = true;
        });
        await other.close();
        expect(socketClosed).toBe(true);
      }
    });
  },
  30000,
);
