encryptionsalt: v1:Q3AzzOKOoAY=:v1:5IJT0AvwBiixS2Qu:OpwOJpGcSwaOcsShqHLOe5pdG8cq0g==
config:
  savia-cloudflare:accountId: 08a0d36f8b0357684f83e4bfeb6628b6
  savia-cloudflare:environment: preview
  savia-cloudflare:publicOrigin: https://savia-preview.hefesoft.com
  savia-cloudflare:documentsBucket: savia-documents-preview
  savia-cloudflare:pagesSearchIndex: savia-pages-search-preview
  cloudflare:apiToken:
    secure: v1:PwnyRkQrlD3090J0:wgImNAImY7PnoGOrlrPEcCjm43xW2XoU7/po+ne8AYnk5W8g2CLbBk6AyMMlaco87F3cwaJc52O/7ekBxarbk1lrWYQm
